Repository OTT-Project/moving, pull requests merged in 2024-11, with the labels that each got.

#4 #4 : 라이브러리 설치
  moving/package-lock.json
  moving/package.json
  moving/src/pages/_app.tsx
Labels: Chore

#6 feat : 네브바 퍼블리싱
  moving/.prettierrc.json
  moving/next.config.ts
  moving/package-lock.json
  moving/package.json
  moving/public/assets/icons/favicon.ico
  moving/public/assets/images/next.svg
  moving/public/icons/dropdownIcon.svg
  moving/public/icons/searchIcon.svg
  moving/public/images/Logo.svg
  moving/src/components/shared/Navbar.tsx
  moving/src/pages/_app.tsx
  moving/src/pages/_document.tsx
  moving/src/pages/index.tsx
  moving/tailwind.config.ts
  moving/tsconfig.json
Labels: Chore, Design

#9 feat#7 : 네브바 배경설정, 테일윈드 공통 컬러 설정
  moving/package-lock.json
  moving/package.json
  moving/src/components/shared/Navbar.tsx
  moving/tailwind.config.ts
Labels: Feat, Chore, Design

#10 Design#8: 모달 퍼블리싱
  moving/package-lock.json
  moving/package.json
  moving/public/icons/favoriteIcon.svg
  moving/public/icons/starIcon.svg
  moving/public/images/modalTestImage.png
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/detail/components/DetailsTab.tsx
  moving/src/components/detail/components/RelatedWorksTab.tsx
  moving/src/components/detail/components/SeriesTab.tsx
  moving/src/components/detail/components/UserReviewsTab.tsx
  moving/src/pages/_app.tsx
  moving/src/styles/globals.css
  moving/tailwind.config.ts
Labels: Feat, Chore, Design

#15 11 : 통일된 영화포스터 형식 api 연동
  moving/next.config.ts
  moving/package-lock.json
  moving/package.json
  moving/src/api/mainpageAPI.tsx
  moving/src/auth/shuffleArray.ts
  moving/src/components/mainPage/ComingSoonMovies.tsx
  moving/src/components/mainPage/gameMovie.tsx
  moving/src/components/mainPage/series.tsx
  moving/src/components/mainPage/todaycontent.tsx
  moving/src/components/mainPage/weeksTrend.tsx
  moving/src/hook/useGameMovie.tsx
  moving/src/hook/useSeriesMovie.tsx
  moving/src/hook/useTodayMovie.tsx
  moving/src/hook/useWeekTrend.tsx
  moving/src/lib/axiosInstance.tsx
  moving/src/pages/mainPage/index.tsx
  moving/src/types/defaultMovie.ts
  moving/store/useGenreStore.tsx
Labels: Feat, Chore, Design

#17 #14: 모달 api 연동
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/detail/components/DetailsTab.tsx
  moving/src/components/detail/components/SeriesTab.tsx
  moving/src/components/modal/ModalFrame.tsx
  moving/src/lib/apis/instance/axiosInstance.ts
  moving/src/lib/apis/modal/api.ts
  moving/src/lib/hook/useModal.ts
  moving/src/pages/test/index.tsx
  moving/src/types/detail/type.ts
  moving/tailwind.config.ts
Labels: Feat

#20 feat: 모달 api 연동
  moving/public/images/defaultImage.png
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/detail/components/DetailsTab.tsx
  moving/src/components/detail/components/RelatedWorksTab.tsx
  moving/src/components/detail/components/SeriesTab.tsx
  moving/src/components/detail/components/UserReviewsTab.tsx
  moving/src/components/modal/ModalFrame.tsx
  moving/src/lib/apis/modal/api.ts
  moving/src/lib/store/modalStore.ts
  moving/src/lib/utils/movieImage.ts
  moving/src/pages/trailerPage/index.tsx
  moving/src/styles/globals.css
  moving/src/types/detail/type.ts
Labels: Feat
