Repository OTT-Project/moving, pull requests merged in 2024-12, with the labels that each got.

#28 드롭다운 디자인 적용
  moving/src/components/mainPage/ComingSoonMovies.tsx
  moving/src/components/mainPage/MainBanner.tsx
  moving/src/components/mainPage/gameMovie.tsx
  moving/src/components/mainPage/popularMovies.tsx
  moving/src/components/mainPage/series.tsx
  moving/src/components/mainPage/todaycontent.tsx
  moving/src/components/mainPage/weeksTrend.tsx
  moving/src/components/shared/Navbar.tsx
  moving/src/hook/mainpage/useGameMovie.tsx
  moving/src/hook/mainpage/usePopularMovie.tsx
  moving/src/hook/mainpage/useRecommendationMovie.tsx
  moving/src/hook/mainpage/useSeriesMovie.tsx
  moving/src/hook/mainpage/useTodayMovie.tsx
  moving/src/hook/mainpage/useUpcomingMovie.tsx
  moving/src/hook/mainpage/useVideos.tsx
  moving/src/hook/mainpage/useWeekTrend.tsx
  moving/src/hook/navBar/useDropdown.tsx
  moving/src/pages/mainPage/index.tsx
  moving/src/styles/globals.css
Labels: Feat

#33 인기 영화 top10 스라이딩 추가
  moving/public/icons/left-arrow-white.svg
  moving/src/components/mainPage/popularMovies.tsx
Labels: Feat

#26 feat: 모달 예고편 페이지 구현
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/detail/components/RelatedWorksTab.tsx
  moving/src/components/detail/components/SeriesTab.tsx
  moving/src/components/detail/components/TrailerTab.tsx
  moving/src/components/detail/components/UserReviewsTab.tsx
  moving/src/lib/apis/modal/api.ts
  moving/src/lib/hook/useModal.ts
  moving/src/lib/hook/useModalData.ts
  moving/src/lib/store/modalAnimateStore.ts
  moving/src/pages/test/index.tsx
  moving/src/pages/trailerPage/index.tsx
Labels: Refactor, Feat

#38 장르 페이지 구현
  moving/package-lock.json
  moving/package.json
  moving/src/api/genreAPI.tsx
  moving/src/components/shared/Navbar.tsx
  moving/src/hook/genre/useGenreMovies.tsx
  moving/src/pages/genre/[genre].tsx
  moving/src/pages/genre/mock.ts
  moving/src/pages/search/[query].tsx
  moving/src/types/genre/genrePage.ts
  moving/src/types/mainPage/defaultMovie.ts
  moving/store/useGenreStore.tsx
Labels: Feat

#43 검색 페이지 api 연동
  moving/src/api/searchAPI.tsx
  moving/src/components/searchPage/RelatedWorks.tsx
  moving/src/components/searchPage/SearchResult.tsx
  moving/src/components/shared/Navbar.tsx
  moving/src/hook/searchpage/useRelatedWorks.tsx
  moving/src/hook/searchpage/usesearch.tsx
  moving/src/pages/genre/[genre].tsx
  moving/src/pages/search/[query].tsx
  moving/src/types/searchPage/searchMovie.ts
Labels: Feat

#44 feat:#40 랜딩페이지 api연동
  moving/package-lock.json
  moving/package.json
  moving/public/images/check.png
  moving/src/components/detail/components/Slider.tsx
  moving/src/components/render/Recent.tsx
  moving/src/pages/index.tsx
Labels: Feat, Design

#41 feat: 모달 리뷰 정렬 기능 구현
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/detail/components/tab/DetailsTab.tsx
  moving/src/components/detail/components/tab/RelatedWorksTab.tsx
  moving/src/components/detail/components/tab/ReviewDropDown.tsx
  moving/src/components/detail/components/tab/SeriesTab.tsx
  moving/src/components/detail/components/tab/TrailerTab.tsx
  moving/src/components/detail/components/tab/UserReviewsTab.tsx
  moving/src/lib/hook/useModalSort.ts
  moving/src/lib/utils/movieReviewStar.ts
  moving/src/lib/utils/reviewTimeAgo.ts
Labels: Feat

#49 메인페이지/장르페이지/검색페이지 반응형 리팩토링
  moving/src/components/mainPage/ComingSoonMovies.tsx
  moving/src/components/mainPage/MainBanner.tsx
  moving/src/components/mainPage/gameMovie.tsx
  moving/src/components/mainPage/membership.tsx
  moving/src/components/mainPage/popularMovies.tsx
  moving/src/components/mainPage/series.tsx
  moving/src/components/mainPage/todaycontent.tsx
  moving/src/components/mainPage/weeksTrend.tsx
  moving/src/components/searchPage/RelatedWorks.tsx
  moving/src/components/searchPage/SearchResult.tsx
  moving/src/components/shared/Navbar.tsx
  moving/src/pages/genre/[genre].tsx
  moving/src/pages/mainPage/index.tsx
  moving/src/styles/globals.css
Labels: Design

#46 feat: 모달 반응형 구현
  moving/public/images/defaultBackPoster.png
  moving/public/images/defaultPoster.png
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/detail/components/tab/DetailsTab.tsx
  moving/src/components/detail/components/tab/RelatedWorksTab.tsx
  moving/src/components/detail/components/tab/ReviewDropDown.tsx
  moving/src/components/detail/components/tab/SeriesTab.tsx
  moving/src/components/detail/components/tab/TrailerTab.tsx
  moving/src/components/detail/components/tab/UserReviewsTab.tsx
  moving/src/components/modal/ModalFrame.tsx
  moving/src/components/searchPage/RelatedWorks.tsx
  moving/src/components/searchPage/SearchResult.tsx
  moving/src/lib/hook/useModal.ts
  moving/src/pages/genre/[genre].tsx
  moving/src/pages/mainPage/index.tsx
  moving/src/pages/test/index.tsx
Labels: Feat

#51 feat: 로딩 스피너 추가
  moving/package-lock.json
  moving/package.json
  moving/src/components/detail/DetailModal.tsx
  moving/src/components/shared/LoadingSpinners.tsx
Labels: Feat

#54 fix : 인기영화 top 10 버그 수정
  moving/src/components/mainPage/popularMovies.tsx
Labels: Fix, Design
